package com.corba.MyApp;


/**
* MyApp/My.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from My.idl
* Thursday, October 21, 2021 10:27:32 PM EAT
*/

public interface My extends MyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface My
