package com.corba.MyApp;

/**
* MyApp/My.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/dowuor/IdeaProjects/ds_class/src/com/corba/My.idl
* Thursday, October 21, 2021 8:24:49 PM EAT
*/

public interface My extends MyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface My
