package com.corba.MyApp;

/**
* MyApp/MyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from My.idl
* Thursday, October 21, 2021 10:27:32 PM EAT
*/

public final class MyHolder implements org.omg.CORBA.portable.Streamable
{
  public My value = null;

  public MyHolder ()
  {
  }

  public MyHolder (My initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyHelper.type ();
  }

}
