package com.corba.MyApp;

/**
* MyApp/MyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/dowuor/IdeaProjects/ds_class/src/com/corba/My.idl
* Thursday, October 21, 2021 8:24:49 PM EAT
*/

public interface MyOperations 
{
  String sayHi ();
  void shutdown ();
} // interface MyOperations
