package com.corba.MyApp;


/**
* MyApp/MyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from My.idl
* Thursday, October 21, 2021 10:27:32 PM EAT
*/

public interface MyOperations 
{
  String sayHi ();
  void shutdown ();
} // interface MyOperations
