package com.corba.MyApp;

/**
* MyApp/MyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/dowuor/IdeaProjects/ds_class/src/com/corba/My.idl
* Thursday, October 21, 2021 8:24:49 PM EAT
*/

public abstract class MyPOA extends org.omg.PortableServer.Servant
 implements MyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHi", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MyApp/My/sayHi
       {
         String $result = null;
         $result = this.sayHi ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // MyApp/My/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MyApp/My:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public My _this() 
  {
    return MyHelper.narrow(
    super._this_object());
  }

  public My _this(org.omg.CORBA.ORB orb) 
  {
    return MyHelper.narrow(
    super._this_object(orb));
  }


} // class MyPOA
